App\Entity\UsersRoles:
    type: entity
    table: users_roles
    indexes:
        user_id:
            columns:
                - user_id
        role_id:
            columns:
                - role_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        role:
            targetEntity: ListRoles
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                role_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: userRoles
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
